USE [master]
GO

/****** Object:  Database [AktivasyonUyg]    Script Date: 31.05.2024 12:43:57 ******/
CREATE DATABASE [AktivasyonUyg]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AktivasyonUyg', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AktivasyonUyg.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AktivasyonUyg_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AktivasyonUyg_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AktivasyonUyg].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AktivasyonUyg] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET ARITHABORT OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AktivasyonUyg] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AktivasyonUyg] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AktivasyonUyg] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AktivasyonUyg] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET RECOVERY FULL 
GO

ALTER DATABASE [AktivasyonUyg] SET  MULTI_USER 
GO

ALTER DATABASE [AktivasyonUyg] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AktivasyonUyg] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AktivasyonUyg] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AktivasyonUyg] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AktivasyonUyg] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AktivasyonUyg] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AktivasyonUyg] SET QUERY_STORE = ON
GO

ALTER DATABASE [AktivasyonUyg] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [AktivasyonUyg] SET  READ_WRITE 
GO

